---
- hosts: web_servers
  become: true
  become_user: root
  tasks:

  - name: download moodle code and index
    shell: |  
     cd /opt
     sudo rm -rf /opt/moodle
     sudo git clone git://git.moodle.org/moodle.git
    become_user: root

  - name: Retrieve a list of each branch available
    shell: |
     cd /opt/moodle
     sudo git branch -a
     sudo git branch --track MOODLE_400_STABLE origin/MOODLE_400_STABLE
     sudo git checkout MOODLE_400_STABLE
    become_user: root

  - name: Copy local repository to /var/www/html/
    shell: |
     sudo cp -R /opt/moodle /var/www/html/
     sudo mkdir /var/moodledata
     sudo chown -R www-data /var/moodledata
     sudo chmod -R 777 /var/moodledata
     sudo chmod -R 0755 /var/www/html/moodle
    become_user: root

  - name: Copy config-dist.php
    template:
     src:  config-dist.php
     dest: /var/www/html/moodle/config.php
     mode: 0755
     owner: root
     group: root



