---

- hosts: database
  become: true
  tasks:

  - name: Ensure PostgreSQL is listening on *
    lineinfile:
     dest: /etc/postgresql/13/main/postgresql.conf
     regexp: '^#listen_addresses\s*='
     line: "listen_addresses='*'"
     state: present

  - name: Add new configuration to "pg_hba.conf"
    blockinfile:
     dest: /etc/postgresql/13/main/pg_hba.conf
     block: |
      host    all             all             10.16.11.0/24                password
