---
- hosts: web_servers
  become: true
  become_user: root

  vars:
    url: "https://moodle.org/plugins/download.php/28571/mod_zoom_moodle41_2023021400.zip"
    plugin_type: "mod"
    filename: "{{ url | basename }}"
    foldername: "{{filename.split('_').0}}"
    search_path: "/var/www/html/moodle/"
  
  tasks:
  - name: Find directory using patterns
    ansible.builtin.find:
      paths: "{{ search_path }}/"
      file_type: directory
      patterns: "{{ plugin_type }}"
      recurse: yes
    register: find_matches

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: find_matches.files[0].path
    when: find_matches is defined

  - name: install plugin
    shell: |
     cd {{ find_matches.files[0].path }}
     wget {{url}}
     unzip {{filename}}
     sudo rm {{filename}}
    #with_items: "{{ find_matches.files }}"

  #- name: install plugin
    #shell: |
      #cd {{ item.path }}
      #wget {{url}}
      #unzip {{filename}}
      #sudo rm {{filename}}         
    #with_items: "{{ find_matches.files }}"
